services:
  docs:
    image: sky_viewer_local_docs
    container_name: sky_viewer_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./sky_viewer:/app/sky_viewer:z
    ports:
      - '9000:9000'
    command: /start-docs
